// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: node.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Node_Internal
	//	*Node_Leaf
	Body          isNode_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetBody() isNode_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Node) GetInternal() *Node_InternalNode {
	if x != nil {
		if x, ok := x.Body.(*Node_Internal); ok {
			return x.Internal
		}
	}
	return nil
}

func (x *Node) GetLeaf() *Node_LeafNode {
	if x != nil {
		if x, ok := x.Body.(*Node_Leaf); ok {
			return x.Leaf
		}
	}
	return nil
}

type isNode_Body interface {
	isNode_Body()
}

type Node_Internal struct {
	Internal *Node_InternalNode `protobuf:"bytes,1,opt,name=internal,proto3,oneof"`
}

type Node_Leaf struct {
	Leaf *Node_LeafNode `protobuf:"bytes,2,opt,name=leaf,proto3,oneof"`
}

func (*Node_Internal) isNode_Body() {}

func (*Node_Leaf) isNode_Body() {}

type Child struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ValueHash     []byte                 `protobuf:"bytes,3,opt,name=valueHash,proto3" json:"valueHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Child) Reset() {
	*x = Child{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Child) ProtoMessage() {}

func (x *Child) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Child.ProtoReflect.Descriptor instead.
func (*Child) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *Child) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Child) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

type Node_InternalNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bitmap        uint32                 `protobuf:"varint,1,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	Children      []*Child               `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node_InternalNode) Reset() {
	*x = Node_InternalNode{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node_InternalNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node_InternalNode) ProtoMessage() {}

func (x *Node_InternalNode) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node_InternalNode.ProtoReflect.Descriptor instead.
func (*Node_InternalNode) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Node_InternalNode) GetBitmap() uint32 {
	if x != nil {
		return x.Bitmap
	}
	return 0
}

func (x *Node_InternalNode) GetChildren() []*Child {
	if x != nil {
		return x.Children
	}
	return nil
}

type Node_LeafNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ValueHash     []byte                 `protobuf:"bytes,2,opt,name=valueHash,proto3" json:"valueHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node_LeafNode) Reset() {
	*x = Node_LeafNode{}
	mi := &file_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node_LeafNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node_LeafNode) ProtoMessage() {}

func (x *Node_LeafNode) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node_LeafNode.ProtoReflect.Descriptor instead.
func (*Node_LeafNode) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Node_LeafNode) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node_LeafNode) GetValueHash() []byte {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\x04node\"\xfb\x01\n" +
	"\x04Node\x125\n" +
	"\binternal\x18\x01 \x01(\v2\x17.node.Node.InternalNodeH\x00R\binternal\x12)\n" +
	"\x04leaf\x18\x02 \x01(\v2\x13.node.Node.LeafNodeH\x00R\x04leaf\x1aO\n" +
	"\fInternalNode\x12\x16\n" +
	"\x06bitmap\x18\x01 \x01(\rR\x06bitmap\x12'\n" +
	"\bchildren\x18\x02 \x03(\v2\v.node.ChildR\bchildren\x1a8\n" +
	"\bLeafNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1c\n" +
	"\tvalueHash\x18\x02 \x01(\fR\tvalueHashB\x06\n" +
	"\x04body\"?\n" +
	"\x05Child\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1c\n" +
	"\tvalueHash\x18\x03 \x01(\fR\tvalueHashB\n" +
	"Z\b./nodepbb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_node_proto_goTypes = []any{
	(*Node)(nil),              // 0: node.Node
	(*Child)(nil),             // 1: node.Child
	(*Node_InternalNode)(nil), // 2: node.Node.InternalNode
	(*Node_LeafNode)(nil),     // 3: node.Node.LeafNode
}
var file_node_proto_depIdxs = []int32{
	2, // 0: node.Node.internal:type_name -> node.Node.InternalNode
	3, // 1: node.Node.leaf:type_name -> node.Node.LeafNode
	1, // 2: node.Node.InternalNode.children:type_name -> node.Child
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_node_proto_msgTypes[0].OneofWrappers = []any{
		(*Node_Internal)(nil),
		(*Node_Leaf)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
